--liquibase formatted sql

--changeset Kazma:1
CREATE TABLE bank_cards (
  card_id BIGINT NOT NULL,
   card_owner VARCHAR(200) NOT NULL,
   date_of_expiry date NOT NULL,
   status_bank_card VARCHAR(100) NOT NULL,
   balance DECIMAL NOT NULL,
   history_transactions FLOAT8[] NOT NULL,
   CONSTRAINT pk_bank_cards PRIMARY KEY (card_id)
);

CREATE TABLE roles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   role_name VARCHAR(255) NOT NULL,
   CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_roles (
  role_id INTEGER NOT NULL,
   user_id BIGINT NOT NULL,
   CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);